name: Solar System Workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup NodeJS Version - 10
              uses: actions/setup-node@v3
              with:
                node-version: 10

            - name: Install Dependencies
              run: npm install

            - name: Unit Testing
              run: npm test